### ISSUE TITLE
UMM Compatibility

### ISSUE THREAD

**Issue by CrackThrough** [ADOFAI-gg/CosmicLoader#2]
The whole UnityModManager compatibility is under the CosmicLoader.UMMCompat project in our solution.

# Todos
## Impl Stage Ⅰ
- [ ] Write tests for UMM Compatibility
- [ ] Support toggling mods
- [ ] Support settings GUI
- [ ] Support ModEntry's Metadata changes and updates in UI

## Impl Stage Ⅱ
- [ ] Mark everything as deprecated
- [ ] Provide migration deadline
- [ ] Display warning when using UMM mods (so people will try to migrate)

## Impl Stage Ⅲ
- [ ] Remove UMM Compatibility 🎉
